apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ingress.yaml
- persistentvolumeclaim.yaml
- postgres-statefulset.yaml
- postgres-secret.yaml
- postgres-service.yaml
- secret.yaml
- service.yaml
- backup-configmap.yaml
- backup.yaml 
- analysistemplate.yaml
- rollout.yaml