apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
      - name: todo-app
        image: todo-app
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "150m"
            memory: "200Mi"
        env:
        - name: GO_PORT
          value: "8080"
        - name: IMAGE_URL
          value: "https://picsum.photos/1200"
        - name: IMAGE_PATH
          value: /usr/src/shared/files/picsum.png
        volumeMounts:
          - name: persistent
            mountPath: /usr/src/shared/files
      - name: todo-backend
        image: todo-backend
        imagePullPolicy: Always
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 5
          httpGet:
            port: 3451
            path: "/healthz"
        ports:
        - containerPort: 8081
        resources:
          limits:
            cpu: "250m"
            memory: "500Mi"
        env:
        - name: BACK_PORT
          value: "8081"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: todo-postgres-secret
              key: DATABASE_URL
        - name: NATS_URL
          value: nats://my-nats.default.svc.cluster.local:4222
      volumes:
      - name: persistent
        persistentVolumeClaim:
          claimName: todo-pvc
