apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- Deployment.yaml
- ingress.yaml
- persistentvolumeclaim.yaml
- postgres-statefulset.yaml
- postgres-secret.yaml
- postgres-service.yaml
- secret.yaml
- service.yaml
