apiVersion: batch/v1 
kind: CronJob 
metadata:
  name: backup 
spec:
  schedule: "23 10 * * *" 
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: docker.io/library/ubuntu:latest
            imagePullPolicy: IfNotPresent
            command: ["/bin/bash", "-c", "chmod +x /tmp/backup_pg_dump.sh && /tmp/backup_pg_dump.sh"]
            env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: todo-postgres-secret
                  key: DATABASE_URL
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: backup-secret
                  key: API_KEY
            volumeMounts:
              - name: backup-config
                mountPath: /tmp/backup_pg_dump.sh
                subPath: backup_pg_dump.sh
          restartPolicy: OnFailure
          volumes:
          - name: backup-config
            configMap:
              name: backup-config
